name: test

on:
  push:
    branches:
      - master

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go:
          - '1.20'
          - '1.21'
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}

      - name: Build
        run: go build -v ./...

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go:
          - '1.20'
          - '1.21'

    services:
      mysql:
        image: mysql:5
        env:
          MYSQL_DATABASE: test
          MYSQL_ROOT_PASSWORD: 123456
        ports:
          - 3306:3306

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}

      - name: Test
        run: go test ./...